Pulling branch v1.0a_EL0 to master
UCSD-E4E/radio_collar_tracker_uib pull request #8
Opened 2020-08-15 00:00 UTC by PlayerEugene

2020-08-17 01:21 UTC, ntlhui requested changes
Please remove all binary files and all dependency files.

2020-08-17 01:21 UTC, ntlhui commented on src/LED_module.c
> +/******************************************************************************
Please add the correct file header - this should include a file overview, license information, and changelog

2020-08-17 01:21 UTC, ntlhui commented on src/LED_module.c
> +};
This seems to be only used in `status_decoder.c`.  If so, why not move it into there?

2020-08-17 01:21 UTC, ntlhui commented on src/LED_module.c
> +uint8_t led_buf;
Are these variables supposed to be global scope?

2020-08-17 01:21 UTC, ntlhui commented on src/LED_module.c
> + */
Can you add some comments about what the initial state of all the LEDs should be after this call?

2020-08-17 01:21 UTC, ntlhui commented on src/LED_module.c
> + * @param[in]  value  The value to set the LED to
What are the permissible values the LED can be set to?

2020-08-17 01:21 UTC, ntlhui commented on src/LED_module.c
> +    static int led_flip[LED_MAPPING_END] = {0, 0, 0, 0, 0};
Why two separate structures?  Can these not be combined?

2020-08-17 01:21 UTC, ntlhui commented on src/LED_module.h
> +#include <stdio.h>
Please add the proper documentation comments/banners

2020-08-17 01:21 UTC, ntlhui commented on src/LED_module.h
> +#define MAX_STATUS 5
What is this supposed to be for?

2020-08-17 01:21 UTC, ntlhui commented on src/LED_module.h
> +} LED_STATE_e;
Where are all of the LED global function prototypes?

2020-08-17 01:21 UTC, ntlhui commented on src/compass_sim.c
>      // FIXME
Why is there still a fixme?

2020-08-17 01:21 UTC, ntlhui commented on src/compass_sim.c
>      // FIXME
Why is there still a fixme?

2020-08-17 01:21 UTC, ntlhui commented on src/compass_sim.c
> +            }
This isn't defined, but aren't 180 and -180 the same?  Would one of these be invalid?

2020-08-17 01:21 UTC, ntlhui commented on src/compass_sim.c
>      // FIXME
Why is there still a fixme here?

2020-08-17 01:21 UTC, ntlhui commented on src/compass_sim.c
>      // FIXME
Why is there still a fixme here?

2020-08-17 01:21 UTC, ntlhui commented on src/main.c
>  #include "compass_sim.h"
Please add file overview documentation and changelog

2020-08-17 01:21 UTC, ntlhui commented on src/main.d
> +nmea.h:
Remove file

2020-08-17 01:21 UTC, ntlhui commented on src/nmea.d
> +nmea.h:
Remove file

2020-08-17 01:21 UTC, ntlhui commented on src/voltageSim.bin
> +�
Remove file

2020-08-17 01:21 UTC, ntlhui commented on src/nmea.c
> + * calculates the latitude solely in degrees then sets the value to the
Should read convert from degrees minutes seconds to decimal decrees instead of solely in degrees

2020-08-17 01:21 UTC, ntlhui commented on src/nmea.c
> +}
Isn't this identical to `findLat`?  If so, can it be merged together?

2020-08-17 01:21 UTC, ntlhui commented on src/nmea.c
> + * longDir changes the longitude to be negative iff the token received is S
Is this for N/S or E/W?

2020-08-17 01:21 UTC, ntlhui commented on src/nmea.c
> +}
Isn't this identical to `fixQuality`?

2020-08-17 01:21 UTC, ntlhui commented on src/nmea.c
> +}
Isn't this identical to `hdop`?

2020-08-17 01:21 UTC, ntlhui commented on src/nmea.c
> +}
Isn't this identical to `hdop`?

2020-08-17 01:21 UTC, ntlhui commented on src/nmea.c
> +}
Aren't these all identical?

2020-08-17 01:21 UTC, ntlhui commented on src/nmea.c
> +}
Aren't these all identical to `dGpsStale`?

2020-08-17 01:21 UTC, ntlhui commented on src/nmea.c
> +                decodeState = DATA_ID;
Probably better to zero out the checksum here as opposed to end of message to denote its initial value.

2020-08-17 01:21 UTC, ntlhui commented on src/nmea.c
> +                    break;
Would it be possible/simpler to simply have a 3 character buffer that is filled then matched against?

2020-08-17 01:21 UTC, ntlhui commented on src/nmea.c
> +                        message = NMEA_MESSAGE_ERROR;
If we are already in error, why not just reset the decoder?

2020-08-17 01:21 UTC, ntlhui commented on src/nmea.c
> +                            break;
Is there a way to make this not as repetitive?  Maybe with a table pointer?

2020-08-17 01:21 UTC, ntlhui commented on src/nmea.h
> +} state_e;
Should this be public or module scope?

2020-08-17 01:21 UTC, ntlhui commented on src/nmea.h
> +} GGA_field_type_e;
Is this used?

2020-08-17 01:21 UTC, ntlhui commented on src/nmea.h
> +} ZDA_field_type_e;
Are these used?

2020-08-17 01:21 UTC, ntlhui commented on src/nmea.h
> +} NMEA_Function_Ptr_t;
Please add docstring.  Also, should this be public or module scope?

2020-08-17 01:21 UTC, ntlhui commented on src/nmea.h
> +}NMEA_Data_u;
Add docstring

2020-08-17 01:21 UTC, ntlhui commented on src/nmea.h
> +extern NMEA_Data_u NMEA_Data;
Add docstring

2020-08-17 01:21 UTC, ntlhui commented on src/sensor_encoder.c
> + * @return     { description_of_the_return_value }
Please describe the return value

2020-08-17 01:21 UTC, ntlhui commented on src/sensor_encoder.c
> + * @return     { description_of_the_return_value }
Please describe return value

2020-08-17 01:21 UTC, ntlhui commented on src/sensor_encoder.c
> +        memcpy(&buf[27], (uint8_t*) &data->payload.voltage, 2);
For the `memcpy`, it would be safer to use `sizeof(type)` instead of fixed values

2020-08-17 01:21 UTC, ntlhui commented on src/sensor_encoder.h
> +#ifndef __SENSOR_ENCODER_H__
Please add file docstring

2020-08-17 01:21 UTC, ntlhui commented on src/sensor_encoder.h
> +} __attribute__((packed)) DataSensorInput_t;
Please add docstrings

2020-08-17 01:21 UTC, ntlhui commented on src/sensor_encoder.h
> +} __attribute__((packed)) DataSensorPacket_t;
Please add docstrings

2020-08-17 01:21 UTC, ntlhui commented on src/sensor_module.c
> +/******************************************************************************
Please add file docstring and changelog

2020-08-17 01:21 UTC, ntlhui commented on src/sensor_module.c
> +extern NMEA_Message_e NMEA_Decode(char c);
Externs should not live in the module - please place in the appropriate headers.

2020-08-17 01:21 UTC, ntlhui commented on src/sensor_module.c
> +    Compass_Sim_Deinit();
Init should occur once in the lifetime of the program, not once per read.

2020-08-17 01:21 UTC, ntlhui commented on src/sensor_module.c
> +    return voltageValue;
Init should occur once in the lifetime of the program, not once per read.

2020-08-17 01:21 UTC, ntlhui commented on src/sensor_module.c
> +    packet->payload.voltage = readVoltage(); //the number in voltageSim.bin (pValue);
These are not constants - the docstring says this function sets the constant portion...

2020-08-17 01:21 UTC, ntlhui commented on src/sensor_module.c
> +}
Is this supposed to do something?

2020-08-17 01:21 UTC, ntlhui commented on src/sensor_module.c
> +    static DataSensorPacket_t packet;
This needs to be handed to the Serial device to output - it's better to declare it as a global instead of function static scope.

2020-08-17 01:21 UTC, ntlhui commented on src/sensor_module.c
> +    packet.payload.fixType = 1;
Why is this hardcoded?

2020-08-17 01:21 UTC, ntlhui commented on src/sensor_module.c
> +        memset(&packet, 0, sizeof(DataSensorPacket_t));
Why are we erasing the packet here??

2020-08-17 01:21 UTC, ntlhui commented on src/sensor_module.h
> +#ifndef __SENSOR_MODULE_H__
Please add docstrings, changelog

2020-08-17 01:21 UTC, ntlhui commented on src/serial_sim.c
> +#include <bits/types/struct_timespec.h>
Check includes

2020-08-17 01:21 UTC, ntlhui commented on src/status_decoder.c
> +extern uint8_t LEDsetState(int index, int value);
Move externs to appropriate header and include

2020-08-17 01:21 UTC, ntlhui commented on src/status_decoder.c
> +int decodeSensorPacket(DataStatusPacket_t* data, uint8_t* buf, uint32_t len)
Why is this decoding a sensor packet?  Also, why are we not decoding this byte by byte?

2020-08-17 01:21 UTC, ntlhui commented on src/status_decoder.c
> +    }
So think about it - we are receiving a bunch of bytes.  The struct `data` is simply a bunch of bytes that should be in exactly the same format as the bytes we are receiving.  Can we not simply interpret the buffer as the struct?

2020-08-17 01:21 UTC, ntlhui commented on src/status_decoder.h
> +#ifndef __STATUS_DECODER_H__
Add file docstring

2020-08-17 01:21 UTC, ntlhui commented on src/status_decoder.h
> +} __attribute__((packed)) DataStatusPacket_t;
Add docstrings

2020-08-17 01:21 UTC, ntlhui commented on src/uibWinBuild.c
> +		}
Already noted in other file, but why aren't we parsing this byte by byte?  There is no guarantee that you will get all 22 bytes in the same read.

2020-08-17 01:21 UTC, ntlhui commented on src/uibWinBuild.c
> +				sensorParse(rxBuf[i]);
Aren't we supposed to send the sensor data somewhere?

2020-08-17 01:21 UTC, ntlhui commented on src/voltage_sim.c
> +    // FIXME
Why is there still a fixme here?

2020-08-17 01:21 UTC, ntlhui commented on src/voltage_sim.c
> +    // FIXME
Why is there still a fixme here?

2020-08-17 01:21 UTC, ntlhui commented on src/voltage_sim.c
> +    // FIXME
Why is there still a fixme here?

2020-08-17 01:21 UTC, ntlhui commented on src/voltage_sim.c
> +    // FIXME
Why is there still a fixme here?

2020-08-17 03:14 UTC, PlayerEugene commented on src/LED_module.c
> +uint8_t led_buf;
No, those variables are supposed to only be used in the LED_module.c file but are used in multiple functions so in order to use them in the LEDInit, LEDsetState, and the LEDcontrol functions, I made the two variables into globals.

2020-08-17 16:27 UTC, ntlhui commented on src/LED_module.c
> +uint8_t led_buf;
ok, please make them module static scope.

2020-08-17 16:35 UTC, ntlhui requested changes

2020-08-17 16:35 UTC, ntlhui commented on src/LED_module.c
> + * @param[in]  value  The value to set the LED to
Is there an enum for these value?

2020-08-20 02:28 UTC, ntlhui requested changes
Please check your changelog entries.

2020-08-20 02:28 UTC, ntlhui commented on src/LED_module.c
> + * @param[in]  value  The value to set the LED to
Please name the enum and set the type for value to that enum.

2020-08-20 02:28 UTC, ntlhui commented on src/uibWinBuild.c
> +extern DataSensorPacket_t sensor_packet;
Externs should be moved to headers

2020-08-20 02:28 UTC, ntlhui commented on src/uibWinBuild.c
> +				sensorParse(rxBuf[i]);
What if we only got a partial message?

2020-08-20 02:28 UTC, ntlhui commented on src/uibWinBuild.c
> +			if(tmp_count >= 22)
What if we start from a partial message?  Please rewrite the `decodeStatusPacket` to work byte by byte.

2020-08-20 02:28 UTC, ntlhui commented on src/sensor_module.h
> +#include "sensor_module.h"
no changelog entry

2020-08-20 02:28 UTC, ntlhui commented on src/serial_sim.c
> -#include <bits/types/struct_timespec.h>
@ntlhui Please check

2020-08-20 02:49 UTC, ntlhui requested changes

2020-08-20 02:49 UTC, ntlhui commented on src/nmea.c
> +}
Would it make more sense to rename this simply `parseU8_0`?

2020-08-20 02:49 UTC, ntlhui commented on src/nmea.c
> +}
Would it make more sense to simply rename this `parseFloat`?

2020-08-20 02:49 UTC, ntlhui commented on src/nmea.c
> +}
Would it make more sense to simply call this `parseU8_FF`?

2020-08-20 02:49 UTC, ntlhui commented on src/nmea.c
> +}
Would it make more sense to simply call this `parseS8`?

2020-08-20 02:49 UTC, ntlhui commented on src/nmea.c
> +}
Would it make more sense to simply call this `parseU32`?

2020-08-20 02:49 UTC, ntlhui commented on src/sensor_module.h
> +extern NMEA_Message_e NMEA_Decode(char c);
Do not mark function prototypes as extern

2020-08-20 02:49 UTC, ntlhui commented on src/sensor_module.c
> +        uint8_t buffer[256];
Do not declare variables partway through a function, please declare this at the top of the function

2020-08-20 02:50 UTC, ntlhui requested changes
Please address changes in unresolved comments

2020-08-24 02:49 UTC, ntlhui approved these changes

2020-08-24 02:49 UTC, merged